### ISSUE TITLE
Insert penalty

### ISSUE THREAD

**Issue by davidmcatee-azure** [tripokey/elm-fuzzy#4]
If I have two matches of the same length, without any letters out of order, they both get the same score (the sum of the add penalties):

![image](https://user-images.githubusercontent.com/18060597/28738717-024fa98a-73aa-11e7-8d0c-2eda3c4bbd75.png)

I would like a way for "Crooked" to get a lower score than "Carob" for the "cro" needle.

Would it be possible to add something like an "Insert Penalty" to achieve this? In the example above, the hay "Carob" would get one insert penalty for inserting the letter "a", and "Crooked" wouldn't get any insert penalty.

**Comment by tripokey** [comment]
I implemented insertPenalty in https://github.com/tripokey/elm-fuzzy/pull/5

Would you mind testing if it suits your needs before i merge it @davidmcatee-azure ?
